version: "3.8"

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.15
    container_name: etcd-single
    command:
      - /usr/local/bin/etcd
      - --name=etcd-single
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-advertise-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd-single=http://0.0.0.0:2380
      - --initial-cluster-token=etcd-cluster-1
      - --initial-cluster-state=new
    ports:
      - "2379:2379" 
      - "2380:2380"
    volumes:
      - etcd-data:/etcd-data

  redis:
    image: redis:7.2-alpine
    container_name: redis-single
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  etcd-data:
  redis-data:
